### ISSUE TITLE
LAN world backup failed

### ISSUE THREAD

**Issue by koalalord9999** [GenPage/Technic#113]
![Issue](http://i.imgur.com/rQQimAs.jpg)

```
[12/25/2015 13:35:40 PM] [13:35:40] [Thread-35/INFO]: §dStarting server backup, expect lag!
[12/25/2015 13:35:40 PM] [13:35:40] [Thread-35/INFO]: Turned off world auto-saving
[12/25/2015 13:35:40 PM] [13:35:40] [Thread-35/INFO]: Saving...
[12/25/2015 13:35:40 PM] [Client thread/INFO]: [CHAT] §dStarting server backup, expect lag!
[12/25/2015 13:35:41 PM] [Client thread/INFO]: [CHAT] [Server: Turned off world auto-saving]
[12/25/2015 13:35:41 PM] [13:35:41] [Thread-35/INFO]: commands.save.flushStart
[12/25/2015 13:35:42 PM] [13:35:42] [Thread-35/INFO]: commands.save.flushEnd
[12/25/2015 13:35:42 PM] [13:35:42] [Thread-35/INFO]: Saved the world
[12/25/2015 13:35:42 PM] [Client thread/INFO]: [CHAT] [Server: Saved the world]
[12/25/2015 13:35:42 PM] [13:35:42] [Thread-35/INFO] [FTBU Backups]: Backing up 95 files...
[12/25/2015 13:35:42 PM] [13:35:42] [Thread-35/INFO] [FTBU Backups]: Compressing 95 files!
[12/25/2015 13:35:42 PM] [13:35:42] [Thread-35/INFO] [FTBU Backups]: [0 | 0.00%]: LAN PARTY\AE2\compass\-834.dat
[12/25/2015 13:35:42 PM] [13:35:42] [Thread-35/INFO]: §4Failed to save world! (java.io.FileNotFoundException)
[12/25/2015 13:35:42 PM] [13:35:42] [Thread-35/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.io.FileNotFoundException: **USERSDIR**\Instances\VanillaMinecraft\saves\LAN PARTY\playerdata\7f9a9d15-ec0c-4dae-a5d0-f4ef6b8dc31f.dat (The system cannot find the file specified)
[12/25/2015 13:35:42 PM] [13:35:42] [Thread-35/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.io.FileInputStream.open0(Native Method)
[12/25/2015 13:35:42 PM] [13:35:42] [Thread-35/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.io.FileInputStream.open(Unknown Source)
[12/25/2015 13:35:42 PM] [13:35:42] [Thread-35/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.io.FileInputStream.<init>(Unknown Source)
[12/25/2015 13:35:42 PM] [13:35:42] [Thread-35/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at latmod.ftbu.world.ThreadBackup.run(ThreadBackup.java:98)
[12/25/2015 13:35:42 PM] [13:35:42] [Client thread/INFO]: [CHAT] §4Failed to save world! (java.io.FileNotFoundException)
[12/25/2015 13:35:42 PM] [13:35:42] [Thread-35/INFO]: Turned on world auto-saving
[12/25/2015 13:35:42 PM] [Client thread/INFO]: [CHAT] [Server: Turned on world auto-saving]
```

**Comment by koalalord9999** [comment]
Looking at it now, it seems it couldn't find a player data? thats kinda weird lol

**Comment by Pyker** [comment]
@koalalord9999 I think you're reporting that in the wrong repository...

**Comment by koalalord9999** [comment]
huh that I am lol
Thought this was the one for aromabackup xD

**Comment by Pyker** [comment]
Nope... this is for a private modpack which isn't current being used. AromaBackup is at https://bitbucket.org/Aroma1997/aromabackup/issues
